### ISSUE TITLE
Lead is not getting created

### ISSUE THREAD

**Issue by ganisivakumar** [robson83/optinmonster-mautic#1]
Hi, I installed this plugin, while i am posting with content-type: "application/json" header, lead is not getting created, but while posting with content-type: "text" header, lead is getting created.What might be the issue?

**Comment by Muhayshi** [comment]
I tried to find out why Mautic does not accept application/json, it seems application/json has to be added to the mime types in the config files but I could not get it to work. however I find a solution around it. you might want to have a look at this script. https://github.com/Muhayshi/optinMonster_mautic_integration

**Comment by ganisivakumar** [comment]
@Muhayshi Thanks, its working

**Comment by BillPackard** [comment]
I try setup but not working. Optinmonster not accept the url, this is a error.
